<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BLL_60MN\BLL_60MN.csproj" />
    <ProjectReference Include="..\Entidades_60MN\Entidades_60MN.csproj" />
    <ProjectReference Include="..\Servicios_60MN\Servicios_60MN.csproj" />
  </ItemGroup>

</Project>